Harmonize tests, tidy up output formatting, use src/libgrace/makeinclude to figure out linking needs.

diff --git a/test/_template/runtest.sh.in b/test/_template/runtest.sh.in
--- a/test/_template/runtest.sh.in
+++ b/test/_template/runtest.sh.in
@@ -1,15 +1,25 @@
 #!/bin/sh
-echo -n "%TESTNAME%: "
+testname=`echo "%TESTNAME%                " | cut -c 1-24`
+echo -n "${testname}: "
 rm -f *.o output.xml >/dev/null 2>&1
+echo -n "."
 make clean >/dev/null 2>&1 || echo -n ""
+echo -n "."
 make > test.log 2>&1 || {
-  echo "failed (BUILD)"
+  echo "   failed (BUILD)"
   exit 1
 }
+echo -n "."
 echo "--- start run" >> test.log
 ./%TESTNAME% >> test.log 2>&1 || {
-  echo "failed (RUN)"
+  echo "  failed (RUN)"
   exit 1
 }
+echo -n "."
+#echo "--- start diff" >> test.log
+#diff out.dat reference.dat >> test.log 2>&1 || {
+#  echo " failed (DIFF)"
+#  exit 1
+#}
 rm -f test.log
-echo "passed"
+echo " passed"
